### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by besartcana** [asmz/SwiftAudioPlayerSample#1]
Its looks perfect thanks. 
Have some questions about remote streaming, how can I get  this working with all functions on remote file?

**Comment by asmz** [comment]
Sorry, the AVAudioPlayer class does not seem to support streaming audio based on HTTP URL.

https://developer.apple.com/documentation/avfoundation/avaudioplayer
>Apple recommends that you use this class for audio playback unless you are playing audio captured from a network stream or require very low I/O latency.

https://developer.apple.com/library/content/qa/qa1634/_index.html
